### PR TITLE
NEW GUI, AUTO SCROLL, ALL DEVICES COMPATIBILITY

### PR DESCRIPTION
**Pull request by logeshhy**
Thanks to @sohelamin ..

This is Updated version

Screenshot

image

### CODE REVIEW

**Comment by sohelamin** [comment]
Thanks for the PR @logeshhy

**Comment by logeshhy** [comment]
Hi,

Can you able to include my site name in there, if you can

freetohack.com

so that i can create few more pull requests

thankyou

**Comment by sohelamin** [comment]
Hi @logeshhy 
You know this is an open source project I can't promote your business here.
The contributions are totally up to you.

**Comment by logeshhy** [comment]
I didn't ask you to promote,  I know how to do that..  Don't try to teach
me..  Thank you...

**Pull request merged**
